/**
 * Copyright (c) 2025 Enzien Audio, Ltd.
 * 
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions, and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the phrase "powered by heavy",
 *    the heavy logo, and a hyperlink to https://enzienaudio.com, all in a visible
 *    form.
 * 
 *   2.1 If the Application is distributed in a store system (for example,
 *       the Apple "App Store" or "Google Play"), the phrase "powered by heavy"
 *       shall be included in the app description or the copyright text as well as
 *       the in the app itself. The heavy logo will shall be visible in the app
 *       itself as well.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */

#ifndef _HEAVY_CONTEXT_OSCILATOR_HPP_
#define _HEAVY_CONTEXT_OSCILATOR_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvControlVar.h"
#include "HvMath.h"
#include "HvControlBinop.h"
#include "HvControlTabread.h"
#include "HvSignalPhasor.h"
#include "HvTable.h"
#include "HvControlUnop.h"
#include "HvControlSystem.h"
#include "HvControlTabwrite.h"
#include "HvControlIf.h"
#include "HvControlPack.h"
#include "HvControlCast.h"
#include "HvSignalVar.h"
#include "HvControlSlice.h"

class Heavy_oscilator : public HeavyContext {

 public:
  Heavy_oscilator(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_oscilator();

  const char *getName() override { return "oscilator"; }
  int getNumInputChannels() override { return 0; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cSlice_OyfiExI1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_szdZLL1Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_fx77tlyX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pDP65RWI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_FyKxDMvI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_SMtGdEda_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_UkJMxis6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lX8T1dLS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_Eql4vg2i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_oHMxIaWN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_0dJqR9nb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_U6BnyBY3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UEpsfZSn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pzDGgWnI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QybsPrIu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SiT30gZG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vrfDbPuz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5SZxbr3z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8BXjYzAS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oCUqkHA0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_P2sq9gCp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_65UPFxM8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MnLvXxRx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VhGTqfn9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KisjK5Mh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_HtHyA7Ag_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3edP2gyt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YqTc5LAw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MEtdNxkP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tFZtpwf2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hXMdEyKK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ekixPhgb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mxVRkbea_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sshzWggy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RpEMnkx6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_s5LvwO2X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_AmbvDKQi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_BiG3Pxde_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_NgHJ2lSY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_H14iFE9o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_LpDW15Do_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_fap0RoWs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kYO98sTH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hJiKir4I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BImEtsoA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7sPjqjg6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_C3RDZy0D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_DSUtjKHH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_72SMDez8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_OMXQXJUf_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_pXSrLX7D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_hX5norEq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_A7j5aF6y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_I34S85zw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_XZsPoPQe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_WcKbochI_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_BcDu7exk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_MS0zZzlj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_5Ki9XshM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_5A3t5pqC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_NljSjr94_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_ssJNiM7O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_ZCK6a8Rg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_2BsmnRUF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_PQkhxaMq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_7XA9ayjP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4HBVA6E3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_jFhymAUO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_UouaRA7q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_TPEajMjI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_Jf4B0dWi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gtQbdZuB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_IpIB6VcW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rm3spKPH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8IGBpzgz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WcPQHF84_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SyJt0ET8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kYBuFrJm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_D9kZAAL1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WnRqXp0R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_07licPn4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_BfjVatE4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabread_1F4O0Crx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_nwkcIfhK_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_KsGDNLp3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_E8yCVlz3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_rbyXws4R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SUDj2EZc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_7glnYAQd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XAMaSQaW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZXczc35f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_W0H6ffef_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ewl7GwMl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabread_uUCSsrPO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_2VCgBNXp_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_MYVY0uaS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_NWVjdYee_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_YErsLsfo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_OFG6jmj8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_74OYjbcg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xnQStXq1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PIKDUfqr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_oFETsmoF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_X0llOVnR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_InuI8nn2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_mx0WBXj2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_D63eNkaF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabread_JHAepwtR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_IdvbLvym_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_iZgIppIm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_0vrPvhiN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_hJJsoKFQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fExriG3z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fyTGutzV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3DdnwVDD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KQAlnVYW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GmtwbPp9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kxKAm3PD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_g3f6IyrN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_VjKa5FIL_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_Cyjd9Q6U_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_T71Haxt3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_2twmAS6m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_bOYjNtUk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_og1bMfUQ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_h1XNnaaV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_EfTFlvgZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_hyOcfGaJ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_dadA4V39_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yKk52p00_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Bv0dE2T5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_lG0gjg37_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_a6R0UN06_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_mkTzUvTf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_y4ThukRr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_U48a95fq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4xlaLx39_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2j9fjdyO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pGQXoXbN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_vCDQIel2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xElUjrcd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_PtPPbFGp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jdi44un2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_m3liIgP4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iENjzuNU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JekiFyXB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rmse6Y2W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_unbs5F5s_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mmbKq7uy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Clo32KFB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rBb34ZiU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_egsrMdaf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2Iu8p8rn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_IA9blfH0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2OlFPK6f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_N0miDQP2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Xv6nWp30_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8nHZcS97_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_QryR0BfX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_sHVoS7FY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_AGzuxDwb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rSi8Phkc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_OaM6yKRK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_nGW5GgAN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_NesYM2UD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_m3FVgQIW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yKH4wAEX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_ZnuyUKZf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_Xahiqdon_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_IGJZrmMN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mj62WLDO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_B5tu9xWI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HjFrCPUr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fdYJ1Drq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4GV9RdDB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_wbzBDMPb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ncUkekMW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_LSgeepVS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2vQgr0yv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DOQIW6Dc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_JY6KGwun_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_Ca4iZ5bZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_yfDZkcBj_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_n8TXjSsV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabread_GIUQMtx7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_RYFGzm5L_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_N32EUb1L_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8XW6ImNE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_6XTKjR7Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_O2GaGqCc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gpqNAtJ8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zTWxpbJU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hbwvm8yL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SgljQv9F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BQ0jypiW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_0uJrJMyI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabread_g45EiKfI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_DPl16UAt_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_fUHh0SI0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_WkZWX2qM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_GiIgdNkN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BwlhS9Uj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ioEUSX06_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SyO1zDEc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JgWYKx4t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GyHLgKGj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_12O1k1IQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nPIbCjpY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NxB3aSCv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YhAwsQZH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_dUkgRhec_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_T8klCp0F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iOmysfcN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_t5Pj7Dco_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_vHBxaSSc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jA0Qer8t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Wy5szmlT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_50R076tR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_w3VFMaVy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZA7hY5x6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5Dw3UV29_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Oem8QGPY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Uncojobu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_7Q4s9u69_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_2Ux4X0D2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_m5Hb3jIa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_rLZI7WcJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FO7GcR8A_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_LvTUQrRF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_VUc0E8cu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_SVMJYFdH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_dcvO8hSv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_i0rK84VC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_YfNkixzB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mlZD7tTQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nMIysJ1I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nCl77CA4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8H30MvuW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_evun0Si8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WooSVJqu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SPIzLO1d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_peqvBbMl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8xF6BMLk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_cnd5aQUU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_KS0ralml_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_pWNAW4I2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_SwYOBoxm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_yoLSqNZN_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_oZ0UBQG6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_sHWRGFWe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_BHaRu3kk_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_e29IinWm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NfOPdQWK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_UA6ocTyI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fhvRVDgF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_6mwu74ue_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_4SnLpIGM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mjHYeRPp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_Q6CS4vbD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_q2JS4jXN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_syIpIb9N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gITDYzFv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_IMlMRQyp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_UGdynH5u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_VhRfAsIW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_oDbc4aMo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9oU5swTU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mlnZPCFQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rrxaWU5n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4Nplzael_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5t9tpNAr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_roA5WKeR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CDoWbJPA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fXji3ZRT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Eid6JHaY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_l6itORnO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_oCvcxc2c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_huGNcOWF_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_1gNtZtwi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_bdxEN2LO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_21taUPIV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_dSrn7Mhx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_S3g6vAoR_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_Z2ZNQ1kL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YnhVUcLw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_d1TlPfTP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_wjZ51R2q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_AZVhY21F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_i2GEUUPy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_sTIzApk2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_Essvpzzl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_3xHzL2kM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_dTdWEODM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_VnIksJEB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_hSRepmzI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ogRxM92i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabread_7789y7SF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_CBOUwBSj_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_TQJ0Ylwn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ky7fTBNm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_KpLtstrt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GzsSS4Y8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CQVklQ3m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dfW1FZ8M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NE2wHN7w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5r6X3yjF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XYZrw796_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabread_yrDUVyM3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_zVgRGAg6_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_ZBkHeBmw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_rW8oWBb4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_OMpbAFru_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_u6TBdN9B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5UZ4a2J5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_JzuXM5Aw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QXzaP0aw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_b2Ipm47a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CutoHqjd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_HeX9YxwM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_yYl6M65p_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_AWahCSRN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabread_SMbAMKZh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_JaWKmLnt_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_2YMOXPvV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Oewi7VnM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_NiIKkvll_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_O0aHfqBw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_75tIlUlB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rVjiOOpM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_b3KupEMg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rMhr5Sq0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QLPPwCzc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_7tYryxHt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_YvkyJicu_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_rnnTIWo4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_cASfqTdh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_PPi3tc4A_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_amtOhOO0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_xoMQG02i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_jASrCI1F_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_A1YbJdow_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_bq46fd6M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_wG9pWkJE_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_b82yW8Sz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ZIm1hLKm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabwrite_gsnF3ELF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_2PdV9jxy_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_YRSXVseO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_G4sfpKej_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_8NSfZI7Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_2csz914V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_9eUFWCxd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_P7Uv29Fm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Jw8KnCTD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zK3OarlH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_TdNLXSOi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_IOoWn9UY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oe7Fev5H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_0qzf5dlr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DyZakPJe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6gOcSMJU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mgeB0GQT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4WifP3dN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kEUhDlZs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xwmCMtGS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BvgZegx1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_it1XHgiu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_0MP7Gslu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_3uSzsZaD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_s1VjRz8u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QqIQbd99_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2zNpbtAs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9TjiUpzZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eIB4UPDb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qVNQSjhc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HzRXn63s_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NgPqu7mN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GZn7kUNG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_w7hzeh3f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SGLisBZt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_e82tjvpC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vjD740E9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_xrVNivPJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fTaxcZaz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_GMnYWxi1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_JlfRMsVX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NwSzSGkl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vfmqlIEl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ap8akXDk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_eQm3zzel_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_jJCzioWa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2RGN912O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hrCexxA1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_K9L9KRB2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6Hh75fqW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_u6f6Q1YO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PIcePpoC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9c1SUyb0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_pUTZBd9F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_wbkTu0AK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_e3thID7G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VDmdHjlf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6Q08VtIU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ClQghk4o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ydcySUE1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3wuTdbRQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_g3NMNw2t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qwMl7tsn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_AkISaG3l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_9ofpcyLW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dbH4GkFb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_cj5xEPUr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dHeNZosh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kbSmsluP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8NJR096l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qaFxXUWO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_cTJ90Sqi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mGTu0Vde_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_yaUrHtmj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_OWoZL6HW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_D85EKmZ1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_C5CCH3SW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_gkOAMu6H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_7bRFnRfg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VWcL3YFh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WZcmxr1Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_a31TwwhE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_AFnPrKGk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TjgTlTXq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pEmJyJ5J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_H5ywhhGO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Vq8sL6FN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xFuFg9PO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dIi5ckR3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ODnedi2o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_bhH65O66_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_HMcP7h6w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_LnqE8L6a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_3BIg37j0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_p9frMpch_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_jeNHm6M2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Q3VXyAPn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_vJjS1xQ6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_aJr8kjZf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_0CnywkIA_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalPhasor sPhasor_9TTFfL4P;
  SignalPhasor sPhasor_bwoGldBa;
  SignalPhasor sPhasor_lSzH15v1;
  SignalPhasor sPhasor_f16rvLdx;
  ControlSlice cSlice_OyfiExI1;
  ControlSlice cSlice_szdZLL1Q;
  ControlSlice cSlice_fx77tlyX;
  ControlVar cVar_pDP65RWI;
  ControlIf cIf_UkJMxis6;
  ControlBinop cBinop_lX8T1dLS;
  ControlIf cIf_Eql4vg2i;
  ControlIf cIf_oHMxIaWN;
  ControlIf cIf_0dJqR9nb;
  ControlIf cIf_U6BnyBY3;
  ControlBinop cBinop_UEpsfZSn;
  ControlBinop cBinop_pzDGgWnI;
  ControlBinop cBinop_QybsPrIu;
  ControlBinop cBinop_oCUqkHA0;
  ControlPack cPack_P2sq9gCp;
  ControlBinop cBinop_65UPFxM8;
  ControlBinop cBinop_MnLvXxRx;
  ControlBinop cBinop_VhGTqfn9;
  ControlBinop cBinop_KisjK5Mh;
  ControlBinop cBinop_3edP2gyt;
  ControlBinop cBinop_YqTc5LAw;
  ControlBinop cBinop_MEtdNxkP;
  ControlBinop cBinop_tFZtpwf2;
  ControlBinop cBinop_ekixPhgb;
  ControlBinop cBinop_mxVRkbea;
  ControlBinop cBinop_sshzWggy;
  ControlBinop cBinop_RpEMnkx6;
  ControlSlice cSlice_AmbvDKQi;
  ControlSlice cSlice_BiG3Pxde;
  ControlSlice cSlice_NgHJ2lSY;
  ControlSlice cSlice_H14iFE9o;
  ControlSlice cSlice_LpDW15Do;
  ControlSlice cSlice_fap0RoWs;
  ControlBinop cBinop_kYO98sTH;
  ControlBinop cBinop_hJiKir4I;
  ControlBinop cBinop_BImEtsoA;
  ControlBinop cBinop_7sPjqjg6;
  ControlSlice cSlice_DSUtjKHH;
  ControlSlice cSlice_72SMDez8;
  ControlSlice cSlice_pXSrLX7D;
  ControlSlice cSlice_hX5norEq;
  ControlSlice cSlice_A7j5aF6y;
  ControlVar cVar_I34S85zw;
  ControlVar cVar_XZsPoPQe;
  ControlSlice cSlice_BcDu7exk;
  ControlSlice cSlice_MS0zZzlj;
  ControlSlice cSlice_5Ki9XshM;
  ControlSlice cSlice_5A3t5pqC;
  ControlVar cVar_NljSjr94;
  ControlIf cIf_ssJNiM7O;
  ControlIf cIf_ZCK6a8Rg;
  ControlIf cIf_2BsmnRUF;
  ControlVar cVar_PQkhxaMq;
  ControlIf cIf_7XA9ayjP;
  ControlBinop cBinop_4HBVA6E3;
  ControlVar cVar_jFhymAUO;
  ControlIf cIf_Jf4B0dWi;
  ControlBinop cBinop_gtQbdZuB;
  ControlBinop cBinop_8IGBpzgz;
  ControlBinop cBinop_kYBuFrJm;
  ControlVar cVar_BfjVatE4;
  ControlTabread cTabread_1F4O0Crx;
  ControlSlice cSlice_KsGDNLp3;
  ControlVar cVar_E8yCVlz3;
  ControlBinop cBinop_SUDj2EZc;
  ControlBinop cBinop_ZXczc35f;
  ControlBinop cBinop_Ewl7GwMl;
  ControlTabread cTabread_uUCSsrPO;
  ControlSlice cSlice_MYVY0uaS;
  ControlVar cVar_NWVjdYee;
  ControlBinop cBinop_OFG6jmj8;
  ControlBinop cBinop_PIKDUfqr;
  ControlBinop cBinop_X0llOVnR;
  ControlVar cVar_InuI8nn2;
  ControlSlice cSlice_mx0WBXj2;
  ControlSlice cSlice_D63eNkaF;
  ControlTabread cTabread_JHAepwtR;
  ControlSlice cSlice_iZgIppIm;
  ControlVar cVar_0vrPvhiN;
  ControlBinop cBinop_fExriG3z;
  ControlBinop cBinop_KQAlnVYW;
  ControlBinop cBinop_kxKAm3PD;
  ControlVar cVar_g3f6IyrN;
  ControlVar cVar_T71Haxt3;
  ControlIf cIf_2twmAS6m;
  ControlTabwrite cTabwrite_bOYjNtUk;
  ControlSlice cSlice_h1XNnaaV;
  ControlTabwrite cTabwrite_EfTFlvgZ;
  ControlSlice cSlice_dadA4V39;
  ControlVar cVar_yKk52p00;
  ControlVar cVar_Bv0dE2T5;
  ControlSlice cSlice_lG0gjg37;
  ControlSlice cSlice_a6R0UN06;
  ControlPack cPack_mkTzUvTf;
  ControlBinop cBinop_iENjzuNU;
  ControlBinop cBinop_JekiFyXB;
  ControlBinop cBinop_rmse6Y2W;
  ControlBinop cBinop_unbs5F5s;
  ControlIf cIf_OaM6yKRK;
  ControlVar cVar_nGW5GgAN;
  ControlIf cIf_NesYM2UD;
  ControlBinop cBinop_m3FVgQIW;
  ControlVar cVar_yKH4wAEX;
  ControlIf cIf_IGJZrmMN;
  ControlBinop cBinop_mj62WLDO;
  ControlBinop cBinop_fdYJ1Drq;
  ControlBinop cBinop_ncUkekMW;
  ControlVar cVar_JY6KGwun;
  ControlTabwrite cTabwrite_Ca4iZ5bZ;
  ControlSlice cSlice_n8TXjSsV;
  ControlTabread cTabread_GIUQMtx7;
  ControlSlice cSlice_N32EUb1L;
  ControlVar cVar_8XW6ImNE;
  ControlBinop cBinop_O2GaGqCc;
  ControlBinop cBinop_hbwvm8yL;
  ControlBinop cBinop_BQ0jypiW;
  ControlIf cIf_0uJrJMyI;
  ControlTabread cTabread_g45EiKfI;
  ControlSlice cSlice_fUHh0SI0;
  ControlVar cVar_WkZWX2qM;
  ControlBinop cBinop_BwlhS9Uj;
  ControlBinop cBinop_JgWYKx4t;
  ControlBinop cBinop_12O1k1IQ;
  ControlIf cIf_2Ux4X0D2;
  ControlVar cVar_m5Hb3jIa;
  ControlIf cIf_rLZI7WcJ;
  ControlBinop cBinop_FO7GcR8A;
  ControlVar cVar_LvTUQrRF;
  ControlIf cIf_dcvO8hSv;
  ControlBinop cBinop_i0rK84VC;
  ControlBinop cBinop_nMIysJ1I;
  ControlBinop cBinop_evun0Si8;
  ControlVar cVar_8xF6BMLk;
  ControlTabwrite cTabwrite_cnd5aQUU;
  ControlSlice cSlice_pWNAW4I2;
  ControlTabwrite cTabwrite_SwYOBoxm;
  ControlSlice cSlice_oZ0UBQG6;
  ControlTabwrite cTabwrite_sHWRGFWe;
  ControlSlice cSlice_e29IinWm;
  ControlIf cIf_Q6CS4vbD;
  ControlVar cVar_q2JS4jXN;
  ControlIf cIf_syIpIb9N;
  ControlBinop cBinop_gITDYzFv;
  ControlVar cVar_IMlMRQyp;
  ControlIf cIf_oDbc4aMo;
  ControlBinop cBinop_9oU5swTU;
  ControlBinop cBinop_4Nplzael;
  ControlBinop cBinop_CDoWbJPA;
  ControlVar cVar_oCvcxc2c;
  ControlVar cVar_bdxEN2LO;
  ControlIf cIf_21taUPIV;
  ControlVar cVar_dSrn7Mhx;
  ControlVar cVar_YnhVUcLw;
  ControlVar cVar_d1TlPfTP;
  ControlIf cIf_wjZ51R2q;
  ControlIf cIf_AZVhY21F;
  ControlPack cPack_i2GEUUPy;
  ControlVar cVar_sTIzApk2;
  ControlSlice cSlice_Essvpzzl;
  ControlSlice cSlice_3xHzL2kM;
  ControlVar cVar_dTdWEODM;
  ControlIf cIf_VnIksJEB;
  ControlVar cVar_hSRepmzI;
  ControlVar cVar_ogRxM92i;
  ControlTabread cTabread_7789y7SF;
  ControlSlice cSlice_TQJ0Ylwn;
  ControlVar cVar_ky7fTBNm;
  ControlBinop cBinop_GzsSS4Y8;
  ControlBinop cBinop_NE2wHN7w;
  ControlBinop cBinop_XYZrw796;
  ControlTabread cTabread_yrDUVyM3;
  ControlSlice cSlice_ZBkHeBmw;
  ControlVar cVar_rW8oWBb4;
  ControlBinop cBinop_u6TBdN9B;
  ControlBinop cBinop_QXzaP0aw;
  ControlBinop cBinop_CutoHqjd;
  ControlTabwrite cTabwrite_HeX9YxwM;
  ControlSlice cSlice_AWahCSRN;
  ControlTabread cTabread_SMbAMKZh;
  ControlSlice cSlice_2YMOXPvV;
  ControlVar cVar_Oewi7VnM;
  ControlBinop cBinop_O0aHfqBw;
  ControlBinop cBinop_b3KupEMg;
  ControlBinop cBinop_QLPPwCzc;
  ControlTabwrite cTabwrite_7tYryxHt;
  ControlSlice cSlice_rnnTIWo4;
  ControlTabwrite cTabwrite_cASfqTdh;
  ControlSlice cSlice_amtOhOO0;
  ControlTabwrite cTabwrite_xoMQG02i;
  ControlSlice cSlice_A1YbJdow;
  ControlTabwrite cTabwrite_bq46fd6M;
  ControlSlice cSlice_b82yW8Sz;
  ControlVar cVar_ZIm1hLKm;
  ControlTabwrite cTabwrite_gsnF3ELF;
  ControlSlice cSlice_YRSXVseO;
  ControlVar cVar_G4sfpKej;
  ControlSlice cSlice_8NSfZI7Y;
  ControlSlice cSlice_2csz914V;
  ControlVar cVar_9eUFWCxd;
  ControlBinop cBinop_P7Uv29Fm;
  ControlBinop cBinop_Jw8KnCTD;
  ControlBinop cBinop_mgeB0GQT;
  ControlBinop cBinop_4WifP3dN;
  ControlBinop cBinop_BvgZegx1;
  ControlBinop cBinop_9TjiUpzZ;
  ControlBinop cBinop_K9L9KRB2;
  ControlBinop cBinop_6Hh75fqW;
  ControlBinop cBinop_mGTu0Vde;
  ControlBinop cBinop_OWoZL6HW;
  ControlBinop cBinop_D85EKmZ1;
  HvTable hTable_C5CCH3SW;
  HvTable hTable_gkOAMu6H;
  HvTable hTable_7bRFnRfg;
  ControlBinop cBinop_TjgTlTXq;
  ControlBinop cBinop_pEmJyJ5J;
  ControlBinop cBinop_Vq8sL6FN;
  ControlBinop cBinop_xFuFg9PO;
  ControlBinop cBinop_dIi5ckR3;
  ControlBinop cBinop_ODnedi2o;
  SignalVarf sVarf_MSnmIugP;
  SignalVarf sVarf_Qtb2pfjZ;
  SignalVarf sVarf_sLxWwvVg;
  SignalVarf sVarf_rQyx0UPr;
};

#endif // _HEAVY_CONTEXT_OSCILATOR_HPP_
